apiVersion: v1
kind: Service
metadata:
  name: opensearch-service
  namespace: opensearch
spec:
  selector:
    app: opensearch
  type: NodePort
  ports:
    - name: http
      port: 9200
      nodePort: 39200
    - name: transport
      port: 9300
