# overlays/development/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
- ../../multi-node/
- ../../storage/local/

patchesStrategicMerge:
- resource-patch.yaml
- replicas-patch.yaml

namespace: opensearch-dev

labels:
- includeSelectors: true
  pairs:
    environment: dev

