apiVersion: batch/v1
kind: Job
metadata:
  name: opensearch-security-init
  namespace: opensearch
spec:
  template:
    spec:
      containers:
      - name: opensearch-security-init
        image: opensearchproject/opensearch:2.9.0
        command: ["/bin/bash", "-c", "/usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh -cd /usr/share/opensearch/config/opensearch-security/ -icl -key /usr/share/opensearch/config/certificates/esnode-key.pem -cert /usr/share/opensearch/config/certificates/esnode.pem -cacert /usr/share/opensearch/config/certificates/root-ca.pem -h opensearch-service -p 9200 -nhnv -icl"]
        volumeMounts:
          - name: opensearch-certs
            mountPath: /usr/share/opensearch/config/certificates
      restartPolicy: OnFailure
      volumes:
        - name: opensearch-certs
          secret:
            secretName: opensearch-certificates
