# opensearch-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
  # namespace: opensearch
data:
  opensearch.yml: |-
    cluster.name: opensearch-cluster
    network.host: 0.0.0.0

    # Security settings
    plugins.security.ssl.transport.pemcert_filepath: esnode.pem
    plugins.security.ssl.transport.pemkey_filepath: esnode-key.pem
    plugins.security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
    plugins.security.ssl.http.pemcert_filepath: esnode.pem
    plugins.security.ssl.http.pemkey_filepath: esnode-key.pem
    plugins.security.ssl.http.pemtrustedcas_filepath: root-ca.pem
    plugins.security.allow_unsafe_democertificates: true
    plugins.security.allow_default_init_securityindex: true
    plugins.security.authcz.admin_dn:
      - CN=kirk,OU=client,O=client,L=test,C=de

    # Node roles
    node.master: ${NODE_MASTER}
    node.data: ${NODE_DATA}
    node.ingest: ${NODE_INGEST}
    
    # Resource limits
    bootstrap.memory_lock: true
    
    # Path settings
    path.data: /usr/share/opensearch/data
    path.logs: /usr/share/opensearch/logs
    
    # Discovery settings
    discovery.seed_hosts: ["opensearch-cluster-master-headless"]
    cluster.initial_master_nodes: ["opensearch-cluster-master-0", "opensearch-cluster-master-1", "opensearch-cluster-master-2"]
    
    # Custom JVM settings
    opensearch.performance.analyzer.enabled: true
    
    # Advanced settings
    action.auto_create_index: ".security*,.opendistro*,.opensearch*,*"
    
  jvm.options: |-
    -Xms${JVM_HEAP_SIZE}
    -Xmx${JVM_HEAP_SIZE}
    -XX:+UseG1GC
    -XX:G1ReservePercent=25
    -XX:InitiatingHeapOccupancyPercent=30
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/usr/share/opensearch/logs/
    -XX:ErrorFile=/usr/share/opensearch/logs/hs_err_pid%p.log
    -XX:+PrintGCDetails
    -XX:+PrintGCDateStamps
    -XX:+PrintTenuringDistribution
    -XX:+PrintGCApplicationStoppedTime
    -Xloggc:/usr/share/opensearch/logs/gc.log
    -XX:+UseGCLogFileRotation
    -XX:NumberOfGCLogFiles=32
    -XX:GCLogFileSize=64m