# base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- secrets.yaml
- dashboard/

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/part-of: opensearch-cluster
