# opensearch-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-credentials
  # namespace: opensearch
type: Opaque
data:
  # Base64 encoded values (echo -n "admin" | base64)
  username: YWRtaW4=
  password: YWRtaW4=

stringData:
  # Security config
  internal-users.yml: |-
    _meta:
      type: "internalusers"
      config_version: 2
    admin:
      hash: "$2y$12$..."  # Generated hash for your password
      reserved: true
      backend_roles:
      - "admin"
      description: "Admin user"
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-certs
type: Opaque
data:
  root-ca.pem: <base64-encoded-root-ca-cert>
  esnode.pem: <base64-encoded-esnode-pem>
  esnode-key.pem: <base64-encoded-esnode-key-pem>
  dashboards.pem: <base64-encoded-dashboards-pem>
  dashboards.key: <base64-encoded-dashboards-key>