# overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml

patchesStrategicMerge:
- resource-patch.yaml
- replicas-patch.yaml

namespace: opensearch-prod

commonLabels:
  environment: production