# overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
- ../../multi-node/
- ../../storage/local/
- ingress.yaml

patchesStrategicMerge:
- resource-patch.yaml
- replicas-patch.yaml

namespace: opensearch-prod

labels:
- includeSelectors: true
  pairs:
    environment: production