# opensearch-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-config
data:
  opensearch.yml: |-
    cluster.name: opensearch-cluster
    network.host: 0.0.0.0
    
    # Discovery settings
    discovery.seed_hosts: ["opensearch-cluster-headless"]

    # Security settings
    plugins.security.allow_unsafe_democertificates: true
    plugins.security.allow_default_init_securityindex: true

    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemtrustedcas_filepath: certificates/root-ca.pem
    plugins.security.ssl.http.pemkey_filepath: certificates/esnode-key.pem
    plugins.security.ssl.http.pemcert_filepath: certificates/esnode.pem

    plugins.security.ssl.transport.enabled: true
    plugins.security.ssl.transport.enforce_hostname_verification: false
    plugins.security.ssl.transport.pemtrustedcas_filepath: certificates/root-ca.pem
    plugins.security.ssl.transport.pemkey_filepath: certificates/esnode-key.pem
    plugins.security.ssl.transport.pemcert_filepath: certificates/esnode.pem

    plugins.security.authcz.admin_dn:
      - 'CN=opensearch.local,O=ExampleOrg,L=SanFrancisco,ST=CA,C=US'
      - 'CN=dashboards.local,O=ExampleOrg,L=SanFrancisco,ST=CA,C=US'

    plugins.security.nodes_dn:
      - 'CN=opensearch,O=UN,L=UN,ST=UN,C=UN'
      - 'CN=dashboards,O=UN,L=UN,ST=UN,C=UN'

    # Single node configuration
    discovery.type: single-node
    
    # Resource limits
    bootstrap.memory_lock: true
    
    # Path settings
    path.data: /usr/share/opensearch/data
    path.logs: /usr/share/opensearch/logs
   
    # Custom JVM settings
    # opensearch.performance.analyzer.enabled: true

    # Advanced settings
    action.auto_create_index: ".security*,.opendistro*,.opensearch*,*"

  jvm.options: |-
    -XX:+UseG1GC
    -XX:G1ReservePercent=25
    -XX:InitiatingHeapOccupancyPercent=30
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath=/usr/share/opensearch/logs/
    -XX:ErrorFile=/usr/share/opensearch/logs/hs_err_pid%p.log
    -XX:+PrintGCDetails
    -Xloggc:/usr/share/opensearch/logs/gc.log
