# opensearch-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: opensearch-cluster
  # namespace: opensearch
  labels:
    app: opensearch
spec:
  selector:
    app: opensearch
  type: NodePort
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    nodePort: 30001
  - name: transport
    port: 9300
    targetPort: 9300