# Single StatefulSet for WSL
# overlays/wsl/single-node.yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch-node
spec:
  serviceName: opensearch-node-headless
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: increase-vm-max-map-count
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/opensearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/opensearch/data
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.9.0
        env:
        - name: cluster.name
          value: opensearch-cluster
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: network.host
          value: "0.0.0.0"
        - name: discovery.type
          value: "single-node"
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: data
          mountPath: /usr/share/opensearch/data
        - name: config
          mountPath: /usr/share/opensearch/config/opensearch.yml
          subPath: opensearch.yml
        - name: config
          mountPath: /usr/share/opensearch/config/jvm.options
          subPath: jvm.options
        - name: certs
          mountPath: /usr/share/opensearch/config/esnode.pem
          subPath: esnode.pem
          readOnly: true
        - name: certs
          mountPath: /usr/share/opensearch/config/esnode-key.pem
          subPath: esnode-key.pem
          readOnly: true
        - name: certs
          mountPath: /usr/share/opensearch/config/root-ca.pem
          subPath: root-ca.pem
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: opensearch-config
      - name: certs
        secret:
          secretName: opensearch-certs
          items:
          - key: esnode.pem
            path: esnode.pem
          - key: esnode-key.pem
            path: esnode-key.pem
          - key: root-ca.pem
            path: root-ca.pem
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-storage
      resources:
        requests:
          storage: 5Gi