apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/
- ../../single-node/
- ../../storage/local/

patches:
- path: resource-patch.yaml
  target:
    kind: StatefulSet
    name: opensearch-node

namespace: opensearch-wsl

labels:
- includeSelectors: true
  pairs:
    environment: wsl
