apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opensearch-wsl

resources:
- ../../base/
- ../../single-node/
- ../../storage/local/
- ingress.yaml

patches:
- path: resource-patch.yaml
  target:
    kind: StatefulSet
    name: opensearch-node

labels:
- includeSelectors: true
  pairs:
    environment: wsl
